import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import SideNavBar from '@/components/sideNavBar'; // Sidebar component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div className={cn(
            "min-h-screen w-full bg-white text-black flex",
            inter.className,
            { "debug-screens": process.env.NODE_ENV === "development" }
        )}>
            <div className="flex w-full">
                <SideNavBar /> {/* Sidebar for dashboard routes */}
                <div className="flex-1 flex flex-col">
                    <main className="flex-1 p-8">
                        {children}
                    </main>
                </div>
            </div>
        </div>
    );
}
